apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  MYSQL_DATABASE: {{.Values.mysql.database}}
  MYSQL_USER: {{.Values.mysql.user}}
  MYSQL_PASSWORD: {{.Values.mysql.password}}
  MYSQL_ROOT_PASSWORD: {{.Values.mysql.rootPassword}}